### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Migushthe2nd** [alew3/faceit_live3#1]
Perhaps a consideration could be made for a faceit_live version for windows devices. Using faceit_live is  currently impossible on a windows machine mainly due to it depending on the v4l2loopback kernel module. [This StackOverflow post](https://stackoverflow.com/a/35935646/12314121) (2017) sums up the possibilities for 'virual cameras' on windows quite nicely. Feel free to close this issue if you are not planning on adding support.

**Comment by alew3** [comment]
I haven't looked into it, but maybe try the OBS Virtual Cam plugin. https://www.youtube.com/watch?v=IT871dHHZRU

**Comment by alew3** [comment]
I put the instructions in the README and changed the code for it to work. You can test it.
