### ISSUE TITLE
No module named 'demo

### ISSUE THREAD

**Issue by rkk16** [alew3/faceit_live3#10]
Getting the above error. How exactly do we install CUDA? I've just downloaded the package and installed it, how do I get cuDNN installed - it's just a zip file?

**Comment by alievk** [comment]
You don't have to install CUDA manually, it comes with Pytorch

**Comment by rkk16** [comment]
ok, what is the 'demo' that's being imported in the python file. I get an error 'no module named demo' and it doesn't run.

**Comment by alew3** [comment]
> ok, what is the 'demo' that's being imported in the python file. I get an error 'no module named demo' and it doesn't run.

It's the neural net from first order model.

You need to checkout all the submodules with the git command as per instructions:

$ git clone --recurse-submodules https://github.com/alew3/faceit_live3.git
