### ISSUE TITLE
Missing usage instruction

### ISSUE THREAD

**Issue by LangBalthazar** [alew3/faceit_live3#11]
Thank you so much for the repo!

I am a first time faceit_live3 user and wonder if i can try to utilize the "Usage" section from the previous https://github.com/alew3/faceit_live to get it running.

After having follow all the setup instructions for win10 i struggle with what to do next but will try with "usage" from the previous version.

The OBS stream part is working just fine with oither sources and installing Cuda went without issues. 

But i cant understand how to train my model or add new person A and B. And the faceit script is not a selectable input in OBS

(running win10, Cuda 10.2, GTX1080)

**Comment by alew3** [comment]
faceit is totally different from faceit_3, I used different neural networks. For faceit_3 I used the First-Order-Model that requires a single picture that you upload to the media folder and no previous training is necessary. You can cycle through the images in the folder by typing 'N'.
