### ISSUE TITLE
linux version feels slow. just wanted to confirm.

### ISSUE THREAD

**Issue by lalamax3d** [alew3/faceit_live3#12]
Hi, using ubuntu 20, GTX 980 Ti card. everything works well but main window (out of 3 pop up windows) feels clearly slow / lagged.

Q. is there a way to speed it up.
I am running it --gpu_id 0 flag. Q. what is best way to confirm, how much GPU it is using.

Also, i have single web camera attached. when using ffplay command with mp4 file. skype easily picks new virtual camera and shows. but when truly running this. skype wasn't showing virtual video device 2. any ideas.

BTW, huge thanks for creating and sharing. (i know, its not issue, just few questions ) feel free to close it, if its causing disturbance. cheers,haseeb

**Comment by alew3** [comment]
It is very computing intensive to do this in real time. Even my Titan RTX suffers :-(
To see the GPU usage you can go under the NVidia Control Panel and select your card. Or type nvidia-smi on the command line.

As for Skype, unfortunately not all programs recognize the virtual camera as a real webcam under Linux. Firefox works for me, but Chrome doesn't.
