### ISSUE TITLE
Can it run on a server?

### ISSUE THREAD

**Issue by streamer-AP** [alew3/faceit_live3#17]
Hi, thank you for your work!  Really cool. 
Now I wonder that can I run this system on a remote GPU server, accepting the video stream from my local desktop.. 
Because my desktop doesn't have a powerful GPU to compute..

**Comment by alew3** [comment]
It should work, but you will have to change the code to read from a video stream instead of from the local webcam. 
You might run into a latency issue because of video buffering on the stream.
