### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by Migushthe2nd** [alew3/faceit_live3#2]
I have tried Python 3.6, 3.7 and 3.8, but for all three a version that satisfies the requirement could not be found for the following modules:
- mkl-fft==1.0.15
- mkl-random==1.1.0
- mkl-service==2.3.0
- pandas==1.0.3
- Pillow==7.0.0
- prometheus-client==0.7.1
- prompt-toolkit==3.0.5
- torch==1.4.0
And at last
- astroid 2.3.3 has requirement wrapt==1.11.*, but you'll have wrapt 1.12.1 which is incompatible.

**Comment by Migushthe2nd** [comment]
I'm not sure this is Conda related, but I will, just to be sure, try [this](https://stackoverflow.com/a/43729857/12314121) tomorrow.

**Comment by alew3** [comment]
What OS and Anaconda version are you running?

**Comment by Migushthe2nd** [comment]
I apparently also had miniconda installed, which was configures in my Path variable. Also, I now ran the commands via the anaconda prompt, and all requirement installed fine. Two things I noticed:

- The python script prints a message which says `R` can be used to switch between relative and abosule, while it should say `T`
- There is no clear indication in the command prompt a key was pressed (N, C, T, Q)

**Comment by alew3** [comment]
Thanks for pointing it out about the text, I changed it on the README, but had forgotten to change it in the code message.

I'm not much of a Windows user, so I did a quick and dirty test yesterday to see if it would run with some changes. It did, but it is much slower than the Linux version and I couldn't get it to fully utilize my GPU. Not sure if this is a Pytorch thing on Windows or a CPU bottleneck because of the preprocessing.

**Comment by alew3** [comment]
@Migushthe2nd apparently Task Manager doesn't report correctly the GPU usage on Windows. You need to use nvidia-smi.exe (you can find it at C:\Program Files\NVIDIA Corporation\NVSMI)
On my Quad-Core 6700K + Titan RTX it was using 26%, so there is definately a CPU bottleneck on my setup.

**Comment by Migushthe2nd** [comment]
Hmm yeah it indeed uses more gpu. Anyways, thank you for your quick assistance!

Also, just noticed another typo at line 120 in `faceit_live.py`:
`cv2.resizeWindow('Stream', webcam_width,webcam_width)`
should be 
`cv2.resizeWindow('Stream', webcam_width,webcam_height)`

**Comment by Jibreel2436** [comment]
> What OS and Anaconda version are you running?

please can you make a youtube video on the tutorials on how to do it please?
