### ISSUE TITLE
Crash when no face is found in camera feed

### ISSUE THREAD

**Issue by Migushthe2nd** [alew3/faceit_live3#3]
![image](https://user-images.githubusercontent.com/22274715/79077909-fc08d580-7d04-11ea-806e-1c711187bbad.png)

`range(detections.shape[2]) == 0` (line 240) is always false, even if no face is detected in the camera feed.

**Comment by alew3** [comment]
fixed it. when no face is found, it cuts out the middle section of the webcam video.
