### ISSUE TITLE
ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by axelina212** [alew3/faceit_live3#8]
Hello,

I've tried getting this to work on windows 10, yet I am stuck when trying to run the following command in Anaconda. 

**"python faceit_live.py"**

The feedback I receive is the following:

**(faceit_live3) D:\School\oi-herkansing\prototype6\faceit_live3>python faceit_live.py
Traceback (most recent call last):
  File "faceit_live.py", line 54, in <module>
    import demo
ModuleNotFoundError: No module named 'demo'**

Could someone help me figure out what i'm doing wrong? I'm very interested to get this working yet I feel frustrated that i'm stuck.
I've tried reinstalling every program as well as redownloading the git folders.

I've tried looking at different threats as well as the older demo for issues but I couldn't find a similar issue.

If I should provide any more information, please let me know. 

Thank you in regards,

Axel van Someren

PS: I've installed Cuda/NVIDA (with the 2 provided links) but i was lost as whether i had to do anything after installing them, such are running them somehow.

**Comment by alew3** [comment]
You are probably missing the /first-order-model folder. 
You need to git clone with the submodules parameter to download that.

$ git clone --recurse-submodules https://github.com/alew3/faceit_live3.git

**Comment by axelina212** [comment]
Thank you, I indeed added everything bar from the submodels. Silly mistake.

Thank you once again for your quick reply
