### ISSUE TITLE
Distorted face

### ISSUE THREAD

**Issue by felartu** [alew3/faceit_live3#9]
Hi,

I'm taking a picture of myself using my webcam, saving the picture into the /media file and then running the software and the end result is a distorted face even though both the source and the webcam feed are very very alike.

What affects the end result of the moving face?

**Comment by alew3** [comment]
Try cropping your photo in a squared ratio, for example: 1000x1000

**Comment by felartu** [comment]
I have the photo in 1:1 ratio at 600px each side, still distorted when I move my face 
![distorted](https://user-images.githubusercontent.com/10916426/80445619-c22df680-88e2-11ea-979e-65c707b25b76.png)

**Comment by alew3** [comment]
@felartu try pressing 'C' to recenter the camera and look directly at the webcam. Did you have the same problem with other images?

**Comment by felartu** [comment]
Pressing 'C' reset it to the original picture but as soon as I move again it gets distorted. It happens with all images.

**Comment by alew3** [comment]
> Pressing 'C' reset it to the original picture but as soon as I move again it gets distorted. It happens with all images.

**Comment by alew3** [comment]
> Pressing 'C' reset it to the original picture but as soon as I move again it gets distorted. It happens with all images.

What's the resolution of your webcam? I'm downsampling to 640x480 to speed up processing, haven't tried the results on a webcam with a different aspect ratio (1.33 to 1) webcam...maybe this is causing the issue?

**Comment by felartu** [comment]
I got a Logitech C930 1080p HD camera to test, is the same result.

Perhaps it needs the source image face to be in a predetermined position? Does it work in dark rooms?
